spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: <facebook-id>
            client-secret: <facebook-secret>
          google:
            client-id: <google-id>
            client-secret: <google-secret>
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ibdb
    password: ibdb
    url: jdbc:sqlserver://localhost;database=ibdb
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_nationalized_character_data: true
        jdbc:
          time_zone: UTC
    database: sql_server

ibdb:
  security:
    non-filtered-prefixes: /oauth, /swagger, /webjars
    oauth2:
      access-token-expiration-in: 5
      access-token-length: 64
      refresh-token-length: 64
      authorization-code-length: 32
  task:
    token-cleanup-frequency: 15