spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        use_nationalized_character_data: true
        jdbc:
          time_zone: UTC
    database: sql_server
    show-sql: true
  datasource:
    initialization-mode: always

ibdb:
  parameters:
    default-page-size: 10
  security:
    non-filtered-prefixes: /oauth, /swagger, /webjars, /public
    oauth2:
      client-id: 73281642736
      access-token-expiration-in: 5
      access-token-length: 64
      refresh-token-length: 64
      authorization-code-length: 32
  task:
    token-cleanup-frequency: 45
---
spring:
  profiles: mssql
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ibdb
    password: ibdb
    url: jdbc:sqlserver://localhost;database=ibdb
    platform: mssql
---
spring:
  profiles: postgresql
  datasource:
    url: jdbc:postgres://tkmijcunlsbsjs:7ae61cb112d9565ed09789a4ac22ea1884258baadeb90b9e70053aea9c5cfcb9@ec2-54-217-235-137.eu-west-1.compute.amazonaws.com:5432/dag8ngcgraul79?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: tkmijcunlsbsjs
    password: 7ae61cb112d9565ed09789a4ac22ea1884258baadeb90b9e70053aea9c5cfcb9
    driver-class-name: org.postgresql.Driver
    platform: postgresql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect